{"error":{"code":141,"message":"INVALID_DATA"},"functionName":"signup","level":"error","message":"Failed running cloud function signup for user undefined with:\n  Input: {\"personImage\":\"\",\"fullname\":\"ssss\",\"email\":\"fs2894488@gmail.com\",\"phone\":\"11 1 1111-1111\",\"password\":\"********\",\"id\":\"RsSgH7jmGy\",\"token\":null}\n  Error: {\"message\":\"INVALID_DATA\",\"code\":141}","params":{"email":"fs2894488@gmail.com","fullname":"ssss","id":"RsSgH7jmGy","password":"********","personImage":"","phone":"11 1 1111-1111","token":null},"timestamp":"2024-04-08T04:08:02.354Z"}
{"code":141,"level":"error","message":"INVALID_DATA","stack":"Error: INVALID_DATA\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-08T04:08:02.364Z"}
{"error":{"code":141,"message":"INVALID_DATA"},"functionName":"signup","level":"error","message":"Failed running cloud function signup for user undefined with:\n  Input: {\"personImage\":\"\",\"fullname\":\"ssss\",\"email\":\"fs2894488@gmail.com\",\"phone\":\"11 1 1111-1111\",\"password\":\"********\",\"id\":\"RsSgH7jmGy\",\"token\":null}\n  Error: {\"message\":\"INVALID_DATA\",\"code\":141}","params":{"email":"fs2894488@gmail.com","fullname":"ssss","id":"RsSgH7jmGy","password":"********","personImage":"","phone":"11 1 1111-1111","token":null},"timestamp":"2024-04-08T04:08:04.188Z"}
{"code":141,"level":"error","message":"INVALID_DATA","stack":"Error: INVALID_DATA\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-08T04:08:04.192Z"}
{"error":{"code":141,"message":"INVALID_DATA"},"functionName":"signup","level":"error","message":"Failed running cloud function signup for user undefined with:\n  Input: {\"personImage\":\"\",\"fullname\":\"ssss\",\"email\":\"fs2894488@gmail.com\",\"phone\":\"11 1 1111-1111\",\"password\":\"********\",\"id\":\"RsSgH7jmGy\",\"token\":null}\n  Error: {\"message\":\"INVALID_DATA\",\"code\":141}","params":{"email":"fs2894488@gmail.com","fullname":"ssss","id":"RsSgH7jmGy","password":"********","personImage":"","phone":"11 1 1111-1111","token":null},"timestamp":"2024-04-08T04:08:05.772Z"}
{"code":141,"level":"error","message":"INVALID_DATA","stack":"Error: INVALID_DATA\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-08T04:08:05.775Z"}
{"error":{"code":141,"message":"INVALID_DATA"},"functionName":"signup","level":"error","message":"Failed running cloud function signup for user undefined with:\n  Input: {\"personImage\":\"\",\"fullname\":\"ssss\",\"email\":\"fs2894488@gmail.com\",\"phone\":\"11 1 1111-1111\",\"password\":\"********\",\"id\":\"RsSgH7jmGy\",\"token\":null}\n  Error: {\"message\":\"INVALID_DATA\",\"code\":141}","params":{"email":"fs2894488@gmail.com","fullname":"ssss","id":"RsSgH7jmGy","password":"********","personImage":"","phone":"11 1 1111-1111","token":null},"timestamp":"2024-04-08T04:08:07.505Z"}
{"code":141,"level":"error","message":"INVALID_DATA","stack":"Error: INVALID_DATA\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-08T04:08:07.530Z"}
{"error":{"code":141,"message":"INVALID_DATA"},"functionName":"signup","level":"error","message":"Failed running cloud function signup for user undefined with:\n  Input: {\"personImage\":\"\",\"fullname\":\"ssss\",\"email\":\"fs2894488@gmail.com\",\"phone\":\"11 1 1111-1111\",\"password\":\"********\",\"id\":\"RsSgH7jmGy\",\"token\":null}\n  Error: {\"message\":\"INVALID_DATA\",\"code\":141}","params":{"email":"fs2894488@gmail.com","fullname":"ssss","id":"RsSgH7jmGy","password":"********","personImage":"","phone":"11 1 1111-1111","token":null},"timestamp":"2024-04-08T04:08:09.938Z"}
{"code":141,"level":"error","message":"INVALID_DATA","stack":"Error: INVALID_DATA\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-08T04:08:09.941Z"}
{"error":{"code":141,"message":"INVALID_DATA"},"functionName":"signup","level":"error","message":"Failed running cloud function signup for user undefined with:\n  Input: {\"personImage\":\"\",\"fullname\":\"ssss\",\"email\":\"fs2894488@gmail.com\",\"phone\":\"11 1 1111-1111\",\"password\":\"********\",\"id\":\"RsSgH7jmGy\",\"token\":null}\n  Error: {\"message\":\"INVALID_DATA\",\"code\":141}","params":{"email":"fs2894488@gmail.com","fullname":"ssss","id":"RsSgH7jmGy","password":"********","personImage":"","phone":"11 1 1111-1111","token":null},"timestamp":"2024-04-08T04:08:13.658Z"}
{"code":141,"level":"error","message":"INVALID_DATA","stack":"Error: INVALID_DATA\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-08T04:08:13.661Z"}
{"error":{"code":141,"message":"INVALID_DATA"},"functionName":"signup","level":"error","message":"Failed running cloud function signup for user undefined with:\n  Input: {\"personImage\":\"\",\"fullname\":\"ssss\",\"email\":\"fs2894488@gmail.com\",\"phone\":\"11 1 1111-1111\",\"password\":\"********\",\"id\":\"RsSgH7jmGy\",\"token\":null}\n  Error: {\"message\":\"INVALID_DATA\",\"code\":141}","params":{"email":"fs2894488@gmail.com","fullname":"ssss","id":"RsSgH7jmGy","password":"********","personImage":"","phone":"11 1 1111-1111","token":null},"timestamp":"2024-04-08T04:08:14.710Z"}
{"code":141,"level":"error","message":"INVALID_DATA","stack":"Error: INVALID_DATA\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-08T04:08:14.713Z"}
{"error":{"code":141,"message":"INVALID_DATA"},"functionName":"signup","level":"error","message":"Failed running cloud function signup for user undefined with:\n  Input: {\"personImage\":\"\",\"fullname\":\"ssss\",\"email\":\"fs2894488@gmail.com\",\"phone\":\"11 1 1111-1111\",\"password\":\"********\",\"id\":\"RsSgH7jmGy\",\"token\":null}\n  Error: {\"message\":\"INVALID_DATA\",\"code\":141}","params":{"email":"fs2894488@gmail.com","fullname":"ssss","id":"RsSgH7jmGy","password":"********","personImage":"","phone":"11 1 1111-1111","token":null},"timestamp":"2024-04-08T04:08:15.525Z"}
{"code":141,"level":"error","message":"INVALID_DATA","stack":"Error: INVALID_DATA\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-08T04:08:15.528Z"}
{"error":{"code":141,"message":"INVALID_DATA"},"functionName":"signup","level":"error","message":"Failed running cloud function signup for user undefined with:\n  Input: {\"personImage\":\"\",\"fullname\":\"ssss\",\"email\":\"fs2894488@gmail.com\",\"phone\":\"11 1 1111-1111\",\"password\":\"********\",\"id\":\"RsSgH7jmGy\",\"token\":null}\n  Error: {\"message\":\"INVALID_DATA\",\"code\":141}","params":{"email":"fs2894488@gmail.com","fullname":"ssss","id":"RsSgH7jmGy","password":"********","personImage":"","phone":"11 1 1111-1111","token":null},"timestamp":"2024-04-08T04:08:16.207Z"}
{"code":141,"level":"error","message":"INVALID_DATA","stack":"Error: INVALID_DATA\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-08T04:08:16.210Z"}
{"error":{"code":141,"message":"INVALID_DATA"},"functionName":"signup","level":"error","message":"Failed running cloud function signup for user undefined with:\n  Input: {\"personImage\":\"\",\"fullname\":\"ssss\",\"email\":\"fs2894488@gmail.com\",\"phone\":\"11 1 1111-1111\",\"password\":\"********\",\"id\":\"RsSgH7jmGy\",\"token\":null}\n  Error: {\"message\":\"INVALID_DATA\",\"code\":141}","params":{"email":"fs2894488@gmail.com","fullname":"ssss","id":"RsSgH7jmGy","password":"********","personImage":"","phone":"11 1 1111-1111","token":null},"timestamp":"2024-04-08T04:08:16.964Z"}
{"code":141,"level":"error","message":"INVALID_DATA","stack":"Error: INVALID_DATA\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-08T04:08:16.978Z"}
{"error":{"code":141,"message":"INVALID_DATA"},"functionName":"signup","level":"error","message":"Failed running cloud function signup for user undefined with:\n  Input: {\"personImage\":\"\",\"fullname\":\"ssss\",\"email\":\"fs2894488@gmail.com\",\"phone\":\"11 1 1111-1111\",\"password\":\"********\",\"id\":\"RsSgH7jmGy\",\"token\":null}\n  Error: {\"message\":\"INVALID_DATA\",\"code\":141}","params":{"email":"fs2894488@gmail.com","fullname":"ssss","id":"RsSgH7jmGy","password":"********","personImage":"","phone":"11 1 1111-1111","token":null},"timestamp":"2024-04-08T04:08:17.630Z"}
{"code":141,"level":"error","message":"INVALID_DATA","stack":"Error: INVALID_DATA\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-08T04:08:17.634Z"}
{"error":{"code":141,"message":"INVALID_DATA"},"functionName":"signup","level":"error","message":"Failed running cloud function signup for user undefined with:\n  Input: {\"personImage\":\"\",\"fullname\":\"ssss\",\"email\":\"fs2894488@gmail.com\",\"phone\":\"11 1 1111-1111\",\"password\":\"********\",\"id\":\"RsSgH7jmGy\",\"token\":null}\n  Error: {\"message\":\"INVALID_DATA\",\"code\":141}","params":{"email":"fs2894488@gmail.com","fullname":"ssss","id":"RsSgH7jmGy","password":"********","personImage":"","phone":"11 1 1111-1111","token":null},"timestamp":"2024-04-08T04:08:18.477Z"}
{"code":141,"level":"error","message":"INVALID_DATA","stack":"Error: INVALID_DATA\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-08T04:08:18.481Z"}
{"error":{"code":141,"message":"INVALID_DATA"},"functionName":"signup","level":"error","message":"Failed running cloud function signup for user undefined with:\n  Input: {\"personImage\":\"\",\"fullname\":\"ssss\",\"email\":\"fs2894488@gmail.com\",\"phone\":\"11 1 1111-1111\",\"password\":\"********\",\"id\":\"RsSgH7jmGy\",\"token\":null}\n  Error: {\"message\":\"INVALID_DATA\",\"code\":141}","params":{"email":"fs2894488@gmail.com","fullname":"ssss","id":"RsSgH7jmGy","password":"********","personImage":"","phone":"11 1 1111-1111","token":null},"timestamp":"2024-04-08T04:08:19.279Z"}
{"code":141,"level":"error","message":"INVALID_DATA","stack":"Error: INVALID_DATA\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-08T04:08:19.282Z"}
{"error":{"code":141,"message":"INVALID_DATA"},"functionName":"signup","level":"error","message":"Failed running cloud function signup for user undefined with:\n  Input: {\"personImage\":\"\",\"fullname\":\"ssss\",\"email\":\"fs2894488@gmail.com\",\"phone\":\"11 1 1111-1111\",\"password\":\"********\",\"id\":\"RsSgH7jmGy\",\"token\":null}\n  Error: {\"message\":\"INVALID_DATA\",\"code\":141}","params":{"email":"fs2894488@gmail.com","fullname":"ssss","id":"RsSgH7jmGy","password":"********","personImage":"","phone":"11 1 1111-1111","token":null},"timestamp":"2024-04-08T04:08:20.061Z"}
{"code":141,"level":"error","message":"INVALID_DATA","stack":"Error: INVALID_DATA\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-08T04:08:20.064Z"}
{"error":{"code":141,"message":"INVALID_DATA"},"functionName":"signup","level":"error","message":"Failed running cloud function signup for user undefined with:\n  Input: {\"personImage\":\"\",\"fullname\":\"ssss\",\"email\":\"fs2894488@gmail.com\",\"phone\":\"11 1 1111-1111\",\"password\":\"********\",\"id\":\"RsSgH7jmGy\",\"token\":null}\n  Error: {\"message\":\"INVALID_DATA\",\"code\":141}","params":{"email":"fs2894488@gmail.com","fullname":"ssss","id":"RsSgH7jmGy","password":"********","personImage":"","phone":"11 1 1111-1111","token":null},"timestamp":"2024-04-08T04:08:20.828Z"}
{"code":141,"level":"error","message":"INVALID_DATA","stack":"Error: INVALID_DATA\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-08T04:08:20.830Z"}
{"error":{"code":141,"message":"INVALID_CREDENTIALS"},"functionName":"login","level":"error","message":"Failed running cloud function login for user undefined with:\n  Input: {\"email\":\"fs2894488@gmail.com\",\"password\":\"********\"}\n  Error: {\"message\":\"INVALID_CREDENTIALS\",\"code\":141}","params":{"email":"fs2894488@gmail.com","password":"********"},"timestamp":"2024-04-08T04:54:51.383Z"}
{"code":141,"level":"error","message":"INVALID_CREDENTIALS","stack":"Error: INVALID_CREDENTIALS\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)","timestamp":"2024-04-08T04:54:51.710Z"}
{"error":{"code":141,"message":"INVALID_CREDENTIALS"},"functionName":"login","level":"error","message":"Failed running cloud function login for user undefined with:\n  Input: {\"email\":\"27106@gmail.com\",\"password\":\"********\"}\n  Error: {\"message\":\"INVALID_CREDENTIALS\",\"code\":141}","params":{"email":"27106@gmail.com","password":"********"},"timestamp":"2024-04-08T04:55:39.727Z"}
{"code":141,"level":"error","message":"INVALID_CREDENTIALS","stack":"Error: INVALID_CREDENTIALS\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-08T04:55:39.740Z"}
{"error":{"code":141,"message":"INVALID_CREDENTIALS"},"functionName":"login","level":"error","message":"Failed running cloud function login for user undefined with:\n  Input: {\"email\":\"27106@gmail.com\",\"password\":\"********\"}\n  Error: {\"message\":\"INVALID_CREDENTIALS\",\"code\":141}","params":{"email":"27106@gmail.com","password":"********"},"timestamp":"2024-04-08T04:55:41.144Z"}
{"code":141,"level":"error","message":"INVALID_CREDENTIALS","stack":"Error: INVALID_CREDENTIALS\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-08T04:55:41.149Z"}
{"error":{"code":141,"message":"INVALID_CREDENTIALS"},"functionName":"login","level":"error","message":"Failed running cloud function login for user undefined with:\n  Input: {\"email\":\"27106@gmail.com\",\"password\":\"********\"}\n  Error: {\"message\":\"INVALID_CREDENTIALS\",\"code\":141}","params":{"email":"27106@gmail.com","password":"********"},"timestamp":"2024-04-08T04:55:42.321Z"}
{"code":141,"level":"error","message":"INVALID_CREDENTIALS","stack":"Error: INVALID_CREDENTIALS\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-08T04:55:42.325Z"}
{"error":{"code":141,"message":"INVALID_CREDENTIALS"},"functionName":"login","level":"error","message":"Failed running cloud function login for user undefined with:\n  Input: {\"email\":\"27106@gmail.com\",\"password\":\"********\"}\n  Error: {\"message\":\"INVALID_CREDENTIALS\",\"code\":141}","params":{"email":"27106@gmail.com","password":"********"},"timestamp":"2024-04-08T04:55:54.508Z"}
{"code":141,"level":"error","message":"INVALID_CREDENTIALS","stack":"Error: INVALID_CREDENTIALS\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-08T04:55:54.511Z"}
{"error":{"code":141,"message":"INVALID_CREDENTIALS"},"functionName":"login","level":"error","message":"Failed running cloud function login for user undefined with:\n  Input: {\"email\":\"27106@gmail.com\",\"password\":\"********\"}\n  Error: {\"message\":\"INVALID_CREDENTIALS\",\"code\":141}","params":{"email":"27106@gmail.com","password":"********"},"timestamp":"2024-04-08T04:55:55.695Z"}
{"code":141,"level":"error","message":"INVALID_CREDENTIALS","stack":"Error: INVALID_CREDENTIALS\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-08T04:55:55.698Z"}
{"error":{"code":141,"message":"INVALID_CREDENTIALS"},"functionName":"login","level":"error","message":"Failed running cloud function login for user undefined with:\n  Input: {\"email\":\"fs27106@gmail.com\",\"password\":\"********\"}\n  Error: {\"message\":\"INVALID_CREDENTIALS\",\"code\":141}","params":{"email":"fs27106@gmail.com","password":"********"},"timestamp":"2024-04-08T04:56:10.857Z"}
{"code":141,"level":"error","message":"INVALID_CREDENTIALS","stack":"Error: INVALID_CREDENTIALS\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)","timestamp":"2024-04-08T04:56:10.861Z"}
