{"error":{"code":141,"message":"INVALID_CREDENTIALS"},"functionName":"login","level":"error","message":"Failed running cloud function login for user undefined with:\n  Input: {\"email\":\"fs27106@gmail.com\",\"password\":\"********\"}\n  Error: {\"message\":\"INVALID_CREDENTIALS\",\"code\":141}","params":{"email":"fs27106@gmail.com","password":"********"},"timestamp":"2024-04-27T11:37:06.250Z"}
{"code":141,"level":"error","message":"INVALID_CREDENTIALS","stack":"Error: INVALID_CREDENTIALS\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-27T11:37:06.259Z"}
{"error":{"code":141,"message":"INVALID_CREDENTIALS"},"functionName":"login","level":"error","message":"Failed running cloud function login for user undefined with:\n  Input: {\"email\":\"fs27106@gmail.com\",\"password\":\"********\"}\n  Error: {\"message\":\"INVALID_CREDENTIALS\",\"code\":141}","params":{"email":"fs27106@gmail.com","password":"********"},"timestamp":"2024-04-27T11:37:14.247Z"}
{"code":141,"level":"error","message":"INVALID_CREDENTIALS","stack":"Error: INVALID_CREDENTIALS\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-27T11:37:14.251Z"}
{"error":{"code":141,"message":"INVALID_CREDENTIALS"},"functionName":"login","level":"error","message":"Failed running cloud function login for user undefined with:\n  Input: {\"email\":\"fs2894488@gmail.com\",\"password\":\"********\"}\n  Error: {\"message\":\"INVALID_CREDENTIALS\",\"code\":141}","params":{"email":"fs2894488@gmail.com","password":"********"},"timestamp":"2024-04-27T11:38:35.944Z"}
{"code":141,"level":"error","message":"INVALID_CREDENTIALS","stack":"Error: INVALID_CREDENTIALS\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-27T11:38:35.948Z"}
{"error":{"code":141,"message":"INVALID_CREDENTIALS"},"functionName":"login","level":"error","message":"Failed running cloud function login for user undefined with:\n  Input: {\"email\":\"fs27106@gmail.com\",\"password\":\"********\"}\n  Error: {\"message\":\"INVALID_CREDENTIALS\",\"code\":141}","params":{"email":"fs27106@gmail.com","password":"********"},"timestamp":"2024-04-27T11:38:47.997Z"}
{"code":141,"level":"error","message":"INVALID_CREDENTIALS","stack":"Error: INVALID_CREDENTIALS\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-27T11:38:48.000Z"}
{"error":{"code":141,"message":"INVALID_CREDENTIALS"},"functionName":"login","level":"error","message":"Failed running cloud function login for user undefined with:\n  Input: {\"email\":\"fs27106@gmail.com\",\"password\":\"********\"}\n  Error: {\"message\":\"INVALID_CREDENTIALS\",\"code\":141}","params":{"email":"fs27106@gmail.com","password":"********"},"timestamp":"2024-04-27T11:38:51.572Z"}
{"code":141,"level":"error","message":"INVALID_CREDENTIALS","stack":"Error: INVALID_CREDENTIALS\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-27T11:38:51.575Z"}
{"error":{"code":141,"message":"INVALID_CREDENTIALS"},"functionName":"login","level":"error","message":"Failed running cloud function login for user undefined with:\n  Input: {\"email\":\"fs27106@gmail.com\",\"password\":\"********\"}\n  Error: {\"message\":\"INVALID_CREDENTIALS\",\"code\":141}","params":{"email":"fs27106@gmail.com","password":"********"},"timestamp":"2024-04-27T11:39:58.389Z"}
{"code":141,"level":"error","message":"INVALID_CREDENTIALS","stack":"Error: INVALID_CREDENTIALS\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-27T11:39:58.394Z"}
{"error":{"code":141,"message":"INVALID_CREDENTIALS"},"functionName":"login","level":"error","message":"Failed running cloud function login for user undefined with:\n  Input: {\"email\":\"fs27106@gmail.com\",\"password\":\"********\"}\n  Error: {\"message\":\"INVALID_CREDENTIALS\",\"code\":141}","params":{"email":"fs27106@gmail.com","password":"********"},"timestamp":"2024-04-27T11:46:00.700Z"}
{"code":141,"level":"error","message":"INVALID_CREDENTIALS","stack":"Error: INVALID_CREDENTIALS\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-27T11:46:00.704Z"}
{"error":{"code":141,"message":"INVALID_CREDENTIALS"},"functionName":"login","level":"error","message":"Failed running cloud function login for user undefined with:\n  Input: {\"email\":\"fs27106@gmail.com\",\"password\":\"********\"}\n  Error: {\"message\":\"INVALID_CREDENTIALS\",\"code\":141}","params":{"email":"fs27106@gmail.com","password":"********"},"timestamp":"2024-04-27T11:48:16.162Z"}
{"code":141,"level":"error","message":"INVALID_CREDENTIALS","stack":"Error: INVALID_CREDENTIALS\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-27T11:48:16.168Z"}
{"error":{"code":141,"message":"INVALID_CREDENTIALS"},"functionName":"login","level":"error","message":"Failed running cloud function login for user undefined with:\n  Input: {\"email\":\"fs27106@gmail.com\",\"password\":\"********\"}\n  Error: {\"message\":\"INVALID_CREDENTIALS\",\"code\":141}","params":{"email":"fs27106@gmail.com","password":"********"},"timestamp":"2024-04-27T11:49:02.737Z"}
{"code":141,"level":"error","message":"INVALID_CREDENTIALS","stack":"Error: INVALID_CREDENTIALS\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-27T11:49:02.785Z"}
{"error":{"code":141,"message":"INVALID_CREDENTIALS"},"functionName":"login","level":"error","message":"Failed running cloud function login for user undefined with:\n  Input: {\"email\":\"fs27106@gmail.com\",\"password\":\"********\"}\n  Error: {\"message\":\"INVALID_CREDENTIALS\",\"code\":141}","params":{"email":"fs27106@gmail.com","password":"********"},"timestamp":"2024-04-27T11:49:05.463Z"}
{"code":141,"level":"error","message":"INVALID_CREDENTIALS","stack":"Error: INVALID_CREDENTIALS\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-27T11:49:05.468Z"}
{"error":{"code":141,"message":"INVALID_CREDENTIALS"},"functionName":"login","level":"error","message":"Failed running cloud function login for user undefined with:\n  Input: {\"email\":\"fs27106@gmail.com\",\"password\":\"********\"}\n  Error: {\"message\":\"INVALID_CREDENTIALS\",\"code\":141}","params":{"email":"fs27106@gmail.com","password":"********"},"timestamp":"2024-04-27T11:55:47.177Z"}
{"code":141,"level":"error","message":"INVALID_CREDENTIALS","stack":"Error: INVALID_CREDENTIALS\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-27T11:55:47.181Z"}
{"error":{"code":141,"message":"Cannot read properties of undefined (reading 'url')"},"functionName":"signup","level":"error","message":"Failed running cloud function signup for user undefined with:\n  Input: {\"email\":\"fs2894488@gmail.com\",\"personImage\":\"B7ACkl3FoH\",\"password\":\"********\",\"fullname\":\"fabio\",\"phone\":\"11 1 1111-1111\"}\n  Error: {\"message\":\"Cannot read properties of undefined (reading 'url')\",\"code\":141}","params":{"email":"fs2894488@gmail.com","fullname":"fabio","password":"********","personImage":"B7ACkl3FoH","phone":"11 1 1111-1111"},"timestamp":"2024-04-27T11:57:12.572Z"}
{"code":141,"level":"error","message":"Cannot read properties of undefined (reading 'url')","stack":"TypeError: Cannot read properties of undefined (reading 'url')\n    at E:\\trabalhoDeGraduacao\\Brasiltoon\\tg\\cloud-brasiltoon\\Brasiltoon\\brasiltoon\\cloud\\functions\\auth.js:25:46\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-27T11:57:12.578Z"}
{"error":{"code":141,"message":"INVALID_CREDENTIALS"},"functionName":"login","level":"error","message":"Failed running cloud function login for user undefined with:\n  Input: {\"email\":\"fs27106@gmail.com\",\"password\":\"********\"}\n  Error: {\"message\":\"INVALID_CREDENTIALS\",\"code\":141}","params":{"email":"fs27106@gmail.com","password":"********"},"timestamp":"2024-04-27T11:57:53.777Z"}
{"code":141,"level":"error","message":"INVALID_CREDENTIALS","stack":"Error: INVALID_CREDENTIALS\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-27T11:57:53.783Z"}
{"error":{"code":141,"message":"INVALID_CREDENTIALS"},"functionName":"login","level":"error","message":"Failed running cloud function login for user undefined with:\n  Input: {\"email\":\"fs2894488@gmail.com\",\"password\":\"********\"}\n  Error: {\"message\":\"INVALID_CREDENTIALS\",\"code\":141}","params":{"email":"fs2894488@gmail.com","password":"********"},"timestamp":"2024-04-27T11:58:04.944Z"}
{"code":141,"level":"error","message":"INVALID_CREDENTIALS","stack":"Error: INVALID_CREDENTIALS\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-27T11:58:04.948Z"}
{"error":{"code":141,"message":"Cannot read properties of undefined (reading 'url')"},"functionName":"signup","level":"error","message":"Failed running cloud function signup for user undefined with:\n  Input: {\"email\":\"fs27106@gmail.com\",\"personImage\":\"ZP60BN0NRp\",\"password\":\"********\",\"fullname\":\"ff\",\"phone\":\"11 1 1111-1111\"}\n  Error: {\"message\":\"Cannot read properties of undefined (reading 'url')\",\"code\":141}","params":{"email":"fs27106@gmail.com","fullname":"ff","password":"********","personImage":"ZP60BN0NRp","phone":"11 1 1111-1111"},"timestamp":"2024-04-27T11:58:53.561Z"}
{"code":141,"level":"error","message":"Cannot read properties of undefined (reading 'url')","stack":"TypeError: Cannot read properties of undefined (reading 'url')\n    at E:\\trabalhoDeGraduacao\\Brasiltoon\\tg\\cloud-brasiltoon\\Brasiltoon\\brasiltoon\\cloud\\functions\\auth.js:25:46\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-27T11:58:53.566Z"}
{"error":{"code":141,"message":"INVALID_CREDENTIALS"},"functionName":"login","level":"error","message":"Failed running cloud function login for user undefined with:\n  Input: {\"email\":\"fs27106@gmail.com\",\"password\":\"********\"}\n  Error: {\"message\":\"INVALID_CREDENTIALS\",\"code\":141}","params":{"email":"fs27106@gmail.com","password":"********"},"timestamp":"2024-04-27T12:02:16.605Z"}
{"code":141,"level":"error","message":"INVALID_CREDENTIALS","stack":"Error: INVALID_CREDENTIALS\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-27T12:02:16.612Z"}
{"error":{"code":141,"message":"INVALID_CREDENTIALS"},"functionName":"login","level":"error","message":"Failed running cloud function login for user undefined with:\n  Input: {\"email\":\"fs27106@gmail.com\",\"password\":\"********\"}\n  Error: {\"message\":\"INVALID_CREDENTIALS\",\"code\":141}","params":{"email":"fs27106@gmail.com","password":"********"},"timestamp":"2024-04-27T12:02:18.771Z"}
{"code":141,"level":"error","message":"INVALID_CREDENTIALS","stack":"Error: INVALID_CREDENTIALS\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-27T12:02:18.778Z"}
{"error":{"code":141,"message":"INVALID_CREDENTIALS"},"functionName":"login","level":"error","message":"Failed running cloud function login for user undefined with:\n  Input: {\"email\":\"fs27106@gmail.com\",\"password\":\"********\"}\n  Error: {\"message\":\"INVALID_CREDENTIALS\",\"code\":141}","params":{"email":"fs27106@gmail.com","password":"********"},"timestamp":"2024-04-27T12:02:42.600Z"}
{"code":141,"level":"error","message":"INVALID_CREDENTIALS","stack":"Error: INVALID_CREDENTIALS\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-27T12:02:42.604Z"}
{"error":{"code":141,"message":"INVALID_CREDENTIALS"},"functionName":"login","level":"error","message":"Failed running cloud function login for user undefined with:\n  Input: {\"email\":\"fs27106@gmail.com\",\"password\":\"********\"}\n  Error: {\"message\":\"INVALID_CREDENTIALS\",\"code\":141}","params":{"email":"fs27106@gmail.com","password":"********"},"timestamp":"2024-04-27T12:07:49.083Z"}
{"code":141,"level":"error","message":"INVALID_CREDENTIALS","stack":"Error: INVALID_CREDENTIALS\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)","timestamp":"2024-04-27T12:07:49.100Z"}
{"error":{"code":141,"message":"INVALID_CREDENTIALS"},"functionName":"login","level":"error","message":"Failed running cloud function login for user undefined with:\n  Input: {\"email\":\"fs27106@gmail.com\",\"password\":\"********\"}\n  Error: {\"message\":\"INVALID_CREDENTIALS\",\"code\":141}","params":{"email":"fs27106@gmail.com","password":"********"},"timestamp":"2024-04-27T12:07:55.673Z"}
{"code":141,"level":"error","message":"INVALID_CREDENTIALS","stack":"Error: INVALID_CREDENTIALS\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)","timestamp":"2024-04-27T12:07:55.686Z"}
{"error":{"code":141,"message":"INVALID_CREDENTIALS"},"functionName":"login","level":"error","message":"Failed running cloud function login for user undefined with:\n  Input: {\"email\":\"fs27106@gmail.com\",\"password\":\"********\"}\n  Error: {\"message\":\"INVALID_CREDENTIALS\",\"code\":141}","params":{"email":"fs27106@gmail.com","password":"********"},"timestamp":"2024-04-27T12:17:32.252Z"}
{"code":141,"level":"error","message":"INVALID_CREDENTIALS","stack":"Error: INVALID_CREDENTIALS\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-27T12:17:32.276Z"}
{"error":{"code":141,"message":"INVALID_CREDENTIALS"},"functionName":"login","level":"error","message":"Failed running cloud function login for user undefined with:\n  Input: {\"email\":\"fs27106@gmail.com\",\"password\":\"********\"}\n  Error: {\"message\":\"INVALID_CREDENTIALS\",\"code\":141}","params":{"email":"fs27106@gmail.com","password":"********"},"timestamp":"2024-04-27T12:18:54.690Z"}
{"code":141,"level":"error","message":"INVALID_CREDENTIALS","stack":"Error: INVALID_CREDENTIALS\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-27T12:18:54.697Z"}
{"error":{"code":141,"message":"INVALID_CREDENTIALS"},"functionName":"login","level":"error","message":"Failed running cloud function login for user undefined with:\n  Input: {\"email\":\"fs27106@gmail.com\",\"password\":\"********\"}\n  Error: {\"message\":\"INVALID_CREDENTIALS\",\"code\":141}","params":{"email":"fs27106@gmail.com","password":"********"},"timestamp":"2024-04-27T12:18:55.888Z"}
{"code":141,"level":"error","message":"INVALID_CREDENTIALS","stack":"Error: INVALID_CREDENTIALS\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-27T12:18:55.894Z"}
{"error":{"code":141,"message":"INVALID_CREDENTIALS"},"functionName":"login","level":"error","message":"Failed running cloud function login for user undefined with:\n  Input: {\"email\":\"fs27106@gmail.com\",\"password\":\"********\"}\n  Error: {\"message\":\"INVALID_CREDENTIALS\",\"code\":141}","params":{"email":"fs27106@gmail.com","password":"********"},"timestamp":"2024-04-27T13:03:57.092Z"}
{"code":141,"level":"error","message":"INVALID_CREDENTIALS","stack":"Error: INVALID_CREDENTIALS\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-27T13:03:57.105Z"}
{"error":{"code":141,"message":"INVALID_CREDENTIALS"},"functionName":"login","level":"error","message":"Failed running cloud function login for user undefined with:\n  Input: {\"email\":\"fs27106@gmail.com\",\"password\":\"********\"}\n  Error: {\"message\":\"INVALID_CREDENTIALS\",\"code\":141}","params":{"email":"fs27106@gmail.com","password":"********"},"timestamp":"2024-04-27T13:04:00.335Z"}
{"code":141,"level":"error","message":"INVALID_CREDENTIALS","stack":"Error: INVALID_CREDENTIALS\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-27T13:04:00.340Z"}
{"error":{"code":141,"message":"INVALID_CREDENTIALS"},"functionName":"login","level":"error","message":"Failed running cloud function login for user undefined with:\n  Input: {\"email\":\"fs27106@gmail.com\",\"password\":\"********\"}\n  Error: {\"message\":\"INVALID_CREDENTIALS\",\"code\":141}","params":{"email":"fs27106@gmail.com","password":"********"},"timestamp":"2024-04-27T13:06:31.160Z"}
{"code":141,"level":"error","message":"INVALID_CREDENTIALS","stack":"Error: INVALID_CREDENTIALS\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-27T13:06:31.173Z"}
{"error":{"code":141,"message":"INVALID_CREDENTIALS"},"functionName":"login","level":"error","message":"Failed running cloud function login for user undefined with:\n  Input: {\"email\":\"fs27106@gmail.com\",\"password\":\"********\"}\n  Error: {\"message\":\"INVALID_CREDENTIALS\",\"code\":141}","params":{"email":"fs27106@gmail.com","password":"********"},"timestamp":"2024-04-27T13:06:34.516Z"}
{"code":141,"level":"error","message":"INVALID_CREDENTIALS","stack":"Error: INVALID_CREDENTIALS\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-27T13:06:34.519Z"}
{"error":{"code":141,"message":"INVALID_USER"},"functionName":"perfil","level":"error","message":"Failed running cloud function perfil for user undefined with:\n  Input: {\"userId\":\"kmu7EcaBH7\"}\n  Error: {\"message\":\"INVALID_USER\",\"code\":141}","params":{"userId":"kmu7EcaBH7"},"timestamp":"2024-04-27T13:11:20.100Z"}
{"code":141,"level":"error","message":"INVALID_USER","stack":"Error: INVALID_USER\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-27T13:11:20.107Z"}
{"error":{"code":141,"message":"INVALID_USER"},"functionName":"perfil","level":"error","message":"Failed running cloud function perfil for user undefined with:\n  Input: {\"userId\":\"kmu7EcaBH7\"}\n  Error: {\"message\":\"INVALID_USER\",\"code\":141}","params":{"userId":"kmu7EcaBH7"},"timestamp":"2024-04-27T13:11:23.111Z"}
{"code":141,"level":"error","message":"INVALID_USER","stack":"Error: INVALID_USER\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-27T13:11:23.117Z"}
{"error":{"code":141,"message":"INVALID_TOKEN"},"functionName":"validate-token","level":"error","message":"Failed running cloud function validate-token for user AeGmyMY6oj with:\n  Input: {}\n  Error: {\"message\":\"INVALID_TOKEN\",\"code\":141}","params":{},"timestamp":"2024-04-27T13:21:38.169Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"INVALID_TOKEN","stack":"Error: INVALID_TOKEN\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-27T13:21:38.173Z"}
{"error":{"code":141,"message":"INVALID_TOKEN"},"functionName":"validate-token","level":"error","message":"Failed running cloud function validate-token for user AeGmyMY6oj with:\n  Input: {}\n  Error: {\"message\":\"INVALID_TOKEN\",\"code\":141}","params":{},"timestamp":"2024-04-27T13:35:14.607Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"INVALID_TOKEN","stack":"Error: INVALID_TOKEN\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-27T13:35:14.615Z"}
{"error":{"code":141,"message":"INVALID_TOKEN"},"functionName":"validate-token","level":"error","message":"Failed running cloud function validate-token for user AeGmyMY6oj with:\n  Input: {}\n  Error: {\"message\":\"INVALID_TOKEN\",\"code\":141}","params":{},"timestamp":"2024-04-27T13:35:14.623Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"INVALID_TOKEN","stack":"Error: INVALID_TOKEN\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-27T13:35:14.658Z"}
{"error":{"code":141,"message":"INVALID_TOKEN"},"functionName":"validate-token","level":"error","message":"Failed running cloud function validate-token for user AeGmyMY6oj with:\n  Input: {}\n  Error: {\"message\":\"INVALID_TOKEN\",\"code\":141}","params":{},"timestamp":"2024-04-27T13:48:34.935Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"INVALID_TOKEN","stack":"Error: INVALID_TOKEN\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-27T13:48:34.940Z"}
{"error":{"code":141,"message":"INVALID_TOKEN"},"functionName":"validate-token","level":"error","message":"Failed running cloud function validate-token for user AeGmyMY6oj with:\n  Input: {}\n  Error: {\"message\":\"INVALID_TOKEN\",\"code\":141}","params":{},"timestamp":"2024-04-27T13:48:34.947Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"INVALID_TOKEN","stack":"Error: INVALID_TOKEN\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-27T13:48:34.952Z"}
{"error":{"code":141,"message":"INVALID_USER"},"functionName":"perfil","level":"error","message":"Failed running cloud function perfil for user undefined with:\n  Input: {\"userId\":\"\"}\n  Error: {\"message\":\"INVALID_USER\",\"code\":141}","params":{"userId":""},"timestamp":"2024-04-27T13:49:04.363Z"}
{"code":141,"level":"error","message":"INVALID_USER","stack":"Error: INVALID_USER\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-27T13:49:04.365Z"}
{"error":{"code":141,"message":"INVALID_USER"},"functionName":"perfil","level":"error","message":"Failed running cloud function perfil for user undefined with:\n  Input: {\"userId\":\"\"}\n  Error: {\"message\":\"INVALID_USER\",\"code\":141}","params":{"userId":""},"timestamp":"2024-04-27T17:58:48.617Z"}
{"code":141,"level":"error","message":"INVALID_USER","stack":"Error: INVALID_USER\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-27T17:58:48.626Z"}
{"error":{"code":141,"message":"INVALID_TOKEN"},"functionName":"validate-token","level":"error","message":"Failed running cloud function validate-token for user AeGmyMY6oj with:\n  Input: {}\n  Error: {\"message\":\"INVALID_TOKEN\",\"code\":141}","params":{},"timestamp":"2024-04-27T17:59:47.480Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"INVALID_TOKEN","stack":"Error: INVALID_TOKEN\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-27T17:59:47.492Z"}
{"error":{"code":141,"message":"INVALID_TOKEN"},"functionName":"validate-token","level":"error","message":"Failed running cloud function validate-token for user AeGmyMY6oj with:\n  Input: {}\n  Error: {\"message\":\"INVALID_TOKEN\",\"code\":141}","params":{},"timestamp":"2024-04-27T17:59:47.498Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"INVALID_TOKEN","stack":"Error: INVALID_TOKEN\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-27T17:59:47.590Z"}
{"error":{"code":141,"message":"INVALID_USER"},"functionName":"perfil","level":"error","message":"Failed running cloud function perfil for user undefined with:\n  Input: {\"userId\":\"\"}\n  Error: {\"message\":\"INVALID_USER\",\"code\":141}","params":{"userId":""},"timestamp":"2024-04-27T18:00:36.072Z"}
{"code":141,"level":"error","message":"INVALID_USER","stack":"Error: INVALID_USER\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-27T18:00:36.074Z"}
{"error":{"code":141,"message":"INVALID_USER"},"functionName":"perfil","level":"error","message":"Failed running cloud function perfil for user undefined with:\n  Input: {\"userId\":\"\"}\n  Error: {\"message\":\"INVALID_USER\",\"code\":141}","params":{"userId":""},"timestamp":"2024-04-27T18:01:10.055Z"}
{"code":141,"level":"error","message":"INVALID_USER","stack":"Error: INVALID_USER\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-27T18:01:10.109Z"}
{"error":{"code":141,"message":"INVALID_TOKEN"},"functionName":"validate-token","level":"error","message":"Failed running cloud function validate-token for user AeGmyMY6oj with:\n  Input: {}\n  Error: {\"message\":\"INVALID_TOKEN\",\"code\":141}","params":{},"timestamp":"2024-04-27T18:10:19.385Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"INVALID_TOKEN","stack":"Error: INVALID_TOKEN\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-27T18:10:19.390Z"}
{"error":{"code":141,"message":"INVALID_TOKEN"},"functionName":"validate-token","level":"error","message":"Failed running cloud function validate-token for user AeGmyMY6oj with:\n  Input: {}\n  Error: {\"message\":\"INVALID_TOKEN\",\"code\":141}","params":{},"timestamp":"2024-04-27T19:57:44.045Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"INVALID_TOKEN","stack":"Error: INVALID_TOKEN\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-27T19:57:44.179Z"}
{"error":{"code":141,"message":"Error deleting objects: ParseError: 101 Object not found."},"functionName":"delete-page","level":"error","message":"Failed running cloud function delete-page for user AeGmyMY6oj with:\n  Input: {\"user\":\"AeGmyMY6oj\",\"pageId\":\"qKskE9rvbv\"}\n  Error: {\"message\":\"Error deleting objects: ParseError: 101 Object not found.\",\"code\":141}","params":{"pageId":"qKskE9rvbv","user":"AeGmyMY6oj"},"timestamp":"2024-04-27T19:59:18.831Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"Error deleting objects: ParseError: 101 Object not found.","stack":"Error: Error deleting objects: ParseError: 101 Object not found.\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-27T19:59:18.836Z"}
{"error":{"code":141,"message":"INVALID_TOKEN"},"functionName":"validate-token","level":"error","message":"Failed running cloud function validate-token for user AeGmyMY6oj with:\n  Input: {}\n  Error: {\"message\":\"INVALID_TOKEN\",\"code\":141}","params":{},"timestamp":"2024-04-27T20:03:05.242Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"INVALID_TOKEN","stack":"Error: INVALID_TOKEN\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-27T20:03:05.245Z"}
{"error":{"code":141,"message":"Error deleting objects: ParseError: 101 Object not found."},"functionName":"delete-page","level":"error","message":"Failed running cloud function delete-page for user AeGmyMY6oj with:\n  Input: {\"user\":\"AeGmyMY6oj\",\"pageId\":\"KO4yROtlQy\"}\n  Error: {\"message\":\"Error deleting objects: ParseError: 101 Object not found.\",\"code\":141}","params":{"pageId":"KO4yROtlQy","user":"AeGmyMY6oj"},"timestamp":"2024-04-27T20:03:48.068Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"Error deleting objects: ParseError: 101 Object not found.","stack":"Error: Error deleting objects: ParseError: 101 Object not found.\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-27T20:03:48.077Z"}
{"error":{"code":141,"message":"Error deleting objects: ParseError: 101 Object not found."},"functionName":"delete-page","level":"error","message":"Failed running cloud function delete-page for user AeGmyMY6oj with:\n  Input: {\"user\":\"AeGmyMY6oj\",\"pageId\":\"qKskE9rvbv\"}\n  Error: {\"message\":\"Error deleting objects: ParseError: 101 Object not found.\",\"code\":141}","params":{"pageId":"qKskE9rvbv","user":"AeGmyMY6oj"},"timestamp":"2024-04-27T21:11:49.348Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"Error deleting objects: ParseError: 101 Object not found.","stack":"Error: Error deleting objects: ParseError: 101 Object not found.\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-27T21:11:49.364Z"}
{"code":209,"level":"error","message":"Invalid session token","stack":"Error: Invalid session token\n    at Object.getAuthForSessionToken (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Auth.js:192:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async handleParseSession (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\middlewares.js:292:21)","timestamp":"2024-04-27T21:13:46.665Z"}
{"error":{"code":141,"message":"Error deleting objects: ParseError: 101 Object not found."},"functionName":"delete-page","level":"error","message":"Failed running cloud function delete-page for user AeGmyMY6oj with:\n  Input: {\"user\":\"AeGmyMY6oj\",\"pageId\":\"qKskE9rvbv\"}\n  Error: {\"message\":\"Error deleting objects: ParseError: 101 Object not found.\",\"code\":141}","params":{"pageId":"qKskE9rvbv","user":"AeGmyMY6oj"},"timestamp":"2024-04-27T21:16:09.595Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"Error deleting objects: ParseError: 101 Object not found.","stack":"Error: Error deleting objects: ParseError: 101 Object not found.\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-27T21:16:09.601Z"}
{"error":{"code":141,"message":"Error deleting objects: ParseError: 101 Object not found."},"functionName":"delete-page","level":"error","message":"Failed running cloud function delete-page for user AeGmyMY6oj with:\n  Input: {\"pageId\":\"qKskE9rvbv\"}\n  Error: {\"message\":\"Error deleting objects: ParseError: 101 Object not found.\",\"code\":141}","params":{"pageId":"qKskE9rvbv"},"timestamp":"2024-04-27T21:17:21.175Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"Error deleting objects: ParseError: 101 Object not found.","stack":"Error: Error deleting objects: ParseError: 101 Object not found.\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-27T21:17:21.178Z"}
{"error":{"code":141,"message":"INVALID_TOKEN"},"functionName":"validate-token","level":"error","message":"Failed running cloud function validate-token for user AeGmyMY6oj with:\n  Input: {}\n  Error: {\"message\":\"INVALID_TOKEN\",\"code\":141}","params":{},"timestamp":"2024-04-27T21:23:24.829Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"INVALID_TOKEN","stack":"Error: INVALID_TOKEN\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-27T21:23:24.884Z"}
