{"error":{"code":141,"message":"INVALID_TOKEN"},"functionName":"validate-token","level":"error","message":"Failed running cloud function validate-token for user AeGmyMY6oj with:\n  Input: {}\n  Error: {\"message\":\"INVALID_TOKEN\",\"code\":141}","params":{},"timestamp":"2024-04-29T18:17:03.479Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"INVALID_TOKEN","stack":"Error: INVALID_TOKEN\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-29T18:17:03.489Z"}
{"error":{"code":141,"message":"INVALID_TOKEN"},"functionName":"validate-token","level":"error","message":"Failed running cloud function validate-token for user AeGmyMY6oj with:\n  Input: {}\n  Error: {\"message\":\"INVALID_TOKEN\",\"code\":141}","params":{},"timestamp":"2024-04-29T18:21:19.151Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"INVALID_TOKEN","stack":"Error: INVALID_TOKEN\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-29T18:21:19.157Z"}
{"error":{"code":141,"message":"INVALID_TOKEN"},"functionName":"validate-token","level":"error","message":"Failed running cloud function validate-token for user AeGmyMY6oj with:\n  Input: {}\n  Error: {\"message\":\"INVALID_TOKEN\",\"code\":141}","params":{},"timestamp":"2024-04-29T18:22:15.671Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"INVALID_TOKEN","stack":"Error: INVALID_TOKEN\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-29T18:22:15.674Z"}
{"error":{"code":141,"message":"INVALID_TOKEN"},"functionName":"validate-token","level":"error","message":"Failed running cloud function validate-token for user AeGmyMY6oj with:\n  Input: {}\n  Error: {\"message\":\"INVALID_TOKEN\",\"code\":141}","params":{},"timestamp":"2024-04-29T18:24:27.792Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"INVALID_TOKEN","stack":"Error: INVALID_TOKEN\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-29T18:24:27.796Z"}
{"code":209,"level":"error","message":"Invalid session token","stack":"Error: Invalid session token\n    at Object.getAuthForSessionToken (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Auth.js:192:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async handleParseSession (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\middlewares.js:292:21)","timestamp":"2024-04-29T18:28:14.719Z"}
{"error":{"code":141,"message":"INVALID_TOKEN"},"functionName":"validate-token","level":"error","message":"Failed running cloud function validate-token for user AeGmyMY6oj with:\n  Input: {}\n  Error: {\"message\":\"INVALID_TOKEN\",\"code\":141}","params":{},"timestamp":"2024-04-29T18:28:34.506Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"INVALID_TOKEN","stack":"Error: INVALID_TOKEN\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-29T18:28:34.508Z"}
{"error":{"code":141,"message":"INVALID_TOKEN"},"functionName":"validate-token","level":"error","message":"Failed running cloud function validate-token for user AeGmyMY6oj with:\n  Input: {}\n  Error: {\"message\":\"INVALID_TOKEN\",\"code\":141}","params":{},"timestamp":"2024-04-29T18:29:03.837Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"INVALID_TOKEN","stack":"Error: INVALID_TOKEN\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-29T18:29:03.839Z"}
{"error":{"code":141,"message":"INVALID_TOKEN"},"functionName":"validate-token","level":"error","message":"Failed running cloud function validate-token for user AeGmyMY6oj with:\n  Input: {}\n  Error: {\"message\":\"INVALID_TOKEN\",\"code\":141}","params":{},"timestamp":"2024-04-29T18:29:07.192Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"INVALID_TOKEN","stack":"Error: INVALID_TOKEN\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)","timestamp":"2024-04-29T18:29:07.199Z"}
{"error":{"code":141,"message":"INVALID_TOKEN"},"functionName":"validate-token","level":"error","message":"Failed running cloud function validate-token for user AeGmyMY6oj with:\n  Input: {}\n  Error: {\"message\":\"INVALID_TOKEN\",\"code\":141}","params":{},"timestamp":"2024-04-29T18:38:57.875Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"INVALID_TOKEN","stack":"Error: INVALID_TOKEN\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-29T18:38:57.889Z"}
{"error":{"code":141,"message":"INVALID_TOKEN"},"functionName":"validate-token","level":"error","message":"Failed running cloud function validate-token for user AeGmyMY6oj with:\n  Input: {}\n  Error: {\"message\":\"INVALID_TOKEN\",\"code\":141}","params":{},"timestamp":"2024-04-29T18:39:00.304Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"INVALID_TOKEN","stack":"Error: INVALID_TOKEN\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)","timestamp":"2024-04-29T18:39:00.312Z"}
{"error":{"code":141,"message":"INVALID_TOKEN"},"functionName":"validate-token","level":"error","message":"Failed running cloud function validate-token for user AeGmyMY6oj with:\n  Input: {}\n  Error: {\"message\":\"INVALID_TOKEN\",\"code\":141}","params":{},"timestamp":"2024-04-29T18:39:48.638Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"INVALID_TOKEN","stack":"Error: INVALID_TOKEN\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-29T18:39:48.644Z"}
{"error":{"code":141,"message":"INVALID_TOKEN"},"functionName":"validate-token","level":"error","message":"Failed running cloud function validate-token for user AeGmyMY6oj with:\n  Input: {}\n  Error: {\"message\":\"INVALID_TOKEN\",\"code\":141}","params":{},"timestamp":"2024-04-29T18:39:50.903Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"INVALID_TOKEN","stack":"Error: INVALID_TOKEN\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)","timestamp":"2024-04-29T18:39:50.906Z"}
{"error":{"code":141,"message":"INVALID_CREDENTIALS"},"functionName":"login","level":"error","message":"Failed running cloud function login for user undefined with:\n  Input: {\"email\":\"fs27106@gmail.com\",\"password\":\"********\"}\n  Error: {\"message\":\"INVALID_CREDENTIALS\",\"code\":141}","params":{"email":"fs27106@gmail.com","password":"********"},"timestamp":"2024-04-29T19:57:18.727Z"}
{"code":141,"level":"error","message":"INVALID_CREDENTIALS","stack":"Error: INVALID_CREDENTIALS\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-29T19:57:18.739Z"}
{"error":{"code":141,"message":"INVALID_CREDENTIALS"},"functionName":"login","level":"error","message":"Failed running cloud function login for user undefined with:\n  Input: {\"email\":\"fs27106@gmail.com\",\"password\":\"********\"}\n  Error: {\"message\":\"INVALID_CREDENTIALS\",\"code\":141}","params":{"email":"fs27106@gmail.com","password":"********"},"timestamp":"2024-04-29T20:00:45.336Z"}
{"code":141,"level":"error","message":"INVALID_CREDENTIALS","stack":"Error: INVALID_CREDENTIALS\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-29T20:00:45.354Z"}
{"error":{"code":141,"message":"INVALID_CREDENTIALS"},"functionName":"login","level":"error","message":"Failed running cloud function login for user undefined with:\n  Input: {\"email\":\"fs27106@gmail.com\",\"password\":\"********\"}\n  Error: {\"message\":\"INVALID_CREDENTIALS\",\"code\":141}","params":{"email":"fs27106@gmail.com","password":"********"},"timestamp":"2024-04-29T20:02:36.642Z"}
{"code":141,"level":"error","message":"INVALID_CREDENTIALS","stack":"Error: INVALID_CREDENTIALS\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-29T20:02:36.657Z"}
{"error":{"code":141,"message":"INVALID_TKEN"},"functionName":"validate-token","level":"error","message":"Failed running cloud function validate-token for user AeGmyMY6oj with:\n  Input: {}\n  Error: {\"message\":\"INVALID_TKEN\",\"code\":141}","params":{},"timestamp":"2024-04-29T20:17:32.581Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"INVALID_TKEN","stack":"Error: INVALID_TKEN\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-29T20:17:32.594Z"}
{"error":{"code":141,"message":"INVALID_TKEN"},"functionName":"validate-token","level":"error","message":"Failed running cloud function validate-token for user AeGmyMY6oj with:\n  Input: {}\n  Error: {\"message\":\"INVALID_TKEN\",\"code\":141}","params":{},"timestamp":"2024-04-29T20:17:34.761Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"INVALID_TKEN","stack":"Error: INVALID_TKEN\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)","timestamp":"2024-04-29T20:17:34.765Z"}
{"error":{"code":141,"message":"INVALID_TKEN"},"functionName":"validate-token","level":"error","message":"Failed running cloud function validate-token for user AeGmyMY6oj with:\n  Input: {}\n  Error: {\"message\":\"INVALID_TKEN\",\"code\":141}","params":{},"timestamp":"2024-04-29T20:18:19.990Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"INVALID_TKEN","stack":"Error: INVALID_TKEN\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-29T20:18:19.995Z"}
{"error":{"code":141,"message":"INVALID_TOKEN"},"functionName":"validate-token","level":"error","message":"Failed running cloud function validate-token for user AeGmyMY6oj with:\n  Input: {}\n  Error: {\"message\":\"INVALID_TOKEN\",\"code\":141}","params":{},"timestamp":"2024-04-29T20:39:10.670Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"INVALID_TOKEN","stack":"Error: INVALID_TOKEN\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-29T20:39:10.701Z"}
{"error":{"code":141,"message":"INVALID_TOKEN"},"functionName":"validate-token","level":"error","message":"Failed running cloud function validate-token for user AeGmyMY6oj with:\n  Input: {}\n  Error: {\"message\":\"INVALID_TOKEN\",\"code\":141}","params":{},"timestamp":"2024-04-29T20:40:51.060Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"INVALID_TOKEN","stack":"Error: INVALID_TOKEN\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-29T20:40:51.075Z"}
{"error":{"code":141,"message":"INVALID_TOKEN"},"functionName":"validate-token","level":"error","message":"Failed running cloud function validate-token for user AeGmyMY6oj with:\n  Input: {}\n  Error: {\"message\":\"INVALID_TOKEN\",\"code\":141}","params":{},"timestamp":"2024-04-29T20:40:53.305Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"INVALID_TOKEN","stack":"Error: INVALID_TOKEN\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)","timestamp":"2024-04-29T20:40:53.311Z"}
{"error":{"code":141,"message":"INVALID_TOKEN"},"functionName":"validate-token","level":"error","message":"Failed running cloud function validate-token for user AeGmyMY6oj with:\n  Input: {}\n  Error: {\"message\":\"INVALID_TOKEN\",\"code\":141}","params":{},"timestamp":"2024-04-29T21:12:49.401Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"INVALID_TOKEN","stack":"Error: INVALID_TOKEN\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-29T21:12:49.410Z"}
{"error":{"code":141,"message":"INVALID_TOKEN"},"functionName":"validate-token","level":"error","message":"Failed running cloud function validate-token for user AeGmyMY6oj with:\n  Input: {}\n  Error: {\"message\":\"INVALID_TOKEN\",\"code\":141}","params":{},"timestamp":"2024-04-29T21:13:14.306Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"INVALID_TOKEN","stack":"Error: INVALID_TOKEN\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-29T21:13:14.310Z"}
{"error":{"code":141,"message":"INVALID_TOKEN"},"functionName":"validate-token","level":"error","message":"Failed running cloud function validate-token for user AeGmyMY6oj with:\n  Input: {}\n  Error: {\"message\":\"INVALID_TOKEN\",\"code\":141}","params":{},"timestamp":"2024-04-29T21:17:13.831Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"INVALID_TOKEN","stack":"Error: INVALID_TOKEN\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-29T21:17:13.847Z"}
{"error":{"code":141,"message":"INVALID_TOKEN"},"functionName":"validate-token","level":"error","message":"Failed running cloud function validate-token for user AeGmyMY6oj with:\n  Input: {}\n  Error: {\"message\":\"INVALID_TOKEN\",\"code\":141}","params":{},"timestamp":"2024-04-29T21:20:30.282Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"INVALID_TOKEN","stack":"Error: INVALID_TOKEN\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-29T21:20:30.300Z"}
{"error":{"code":141,"message":"INVALID_TOKEN"},"functionName":"validate-token","level":"error","message":"Failed running cloud function validate-token for user AeGmyMY6oj with:\n  Input: {}\n  Error: {\"message\":\"INVALID_TOKEN\",\"code\":141}","params":{},"timestamp":"2024-04-29T21:20:33.430Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"INVALID_TOKEN","stack":"Error: INVALID_TOKEN\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)","timestamp":"2024-04-29T21:20:33.435Z"}
{"error":{"code":141,"message":"INVALID_TOKEN"},"functionName":"validate-token","level":"error","message":"Failed running cloud function validate-token for user AeGmyMY6oj with:\n  Input: {}\n  Error: {\"message\":\"INVALID_TOKEN\",\"code\":141}","params":{},"timestamp":"2024-04-29T21:21:14.136Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"INVALID_TOKEN","stack":"Error: INVALID_TOKEN\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-29T21:21:14.141Z"}
{"error":{"code":141,"message":"INVALID_TOKEN"},"functionName":"validate-token","level":"error","message":"Failed running cloud function validate-token for user AeGmyMY6oj with:\n  Input: {}\n  Error: {\"message\":\"INVALID_TOKEN\",\"code\":141}","params":{},"timestamp":"2024-04-29T21:26:55.948Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"INVALID_TOKEN","stack":"Error: INVALID_TOKEN\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-29T21:26:56.010Z"}
{"error":{"code":141,"message":"INVALID_TOKEN"},"functionName":"validate-token","level":"error","message":"Failed running cloud function validate-token for user AeGmyMY6oj with:\n  Input: {}\n  Error: {\"message\":\"INVALID_TOKEN\",\"code\":141}","params":{},"timestamp":"2024-04-29T21:27:17.477Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"INVALID_TOKEN","stack":"Error: INVALID_TOKEN\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-29T21:27:17.501Z"}
{"error":{"code":141,"message":"INVALID_TOKEN"},"functionName":"validate-token","level":"error","message":"Failed running cloud function validate-token for user AeGmyMY6oj with:\n  Input: {}\n  Error: {\"message\":\"INVALID_TOKEN\",\"code\":141}","params":{},"timestamp":"2024-04-29T21:27:57.622Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"INVALID_TOKEN","stack":"Error: INVALID_TOKEN\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-29T21:27:57.628Z"}
{"error":{"code":141,"message":"INVALID_TOKEN"},"functionName":"validate-token","level":"error","message":"Failed running cloud function validate-token for user AeGmyMY6oj with:\n  Input: {}\n  Error: {\"message\":\"INVALID_TOKEN\",\"code\":141}","params":{},"timestamp":"2024-04-29T21:31:54.708Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"INVALID_TOKEN","stack":"Error: INVALID_TOKEN\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-29T21:31:54.727Z"}
{"error":{"code":141,"message":"INVALID_TOKEN"},"functionName":"validate-token","level":"error","message":"Failed running cloud function validate-token for user AeGmyMY6oj with:\n  Input: {}\n  Error: {\"message\":\"INVALID_TOKEN\",\"code\":141}","params":{},"timestamp":"2024-04-29T21:33:28.347Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"INVALID_TOKEN","stack":"Error: INVALID_TOKEN\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-29T21:33:28.362Z"}
{"error":{"code":141,"message":"INVALID_TOKEN"},"functionName":"validate-token","level":"error","message":"Failed running cloud function validate-token for user AeGmyMY6oj with:\n  Input: {}\n  Error: {\"message\":\"INVALID_TOKEN\",\"code\":141}","params":{},"timestamp":"2024-04-29T21:38:09.508Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"INVALID_TOKEN","stack":"Error: INVALID_TOKEN\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-29T21:38:09.526Z"}
{"error":{"code":141,"message":"INVALID_TKEN"},"functionName":"validate-token","level":"error","message":"Failed running cloud function validate-token for user AeGmyMY6oj with:\n  Input: {}\n  Error: {\"message\":\"INVALID_TKEN\",\"code\":141}","params":{},"timestamp":"2024-04-29T21:40:24.815Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"INVALID_TKEN","stack":"Error: INVALID_TKEN\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-29T21:40:24.831Z"}
{"error":{"code":141,"message":"INVALID_TOKEN"},"functionName":"validate-token","level":"error","message":"Failed running cloud function validate-token for user AeGmyMY6oj with:\n  Input: {}\n  Error: {\"message\":\"INVALID_TOKEN\",\"code\":141}","params":{},"timestamp":"2024-04-29T21:47:59.910Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"INVALID_TOKEN","stack":"Error: INVALID_TOKEN\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-29T21:47:59.923Z"}
{"error":{"code":141,"message":"INVALID_TOKEN"},"functionName":"validate-token","level":"error","message":"Failed running cloud function validate-token for user AeGmyMY6oj with:\n  Input: {}\n  Error: {\"message\":\"INVALID_TOKEN\",\"code\":141}","params":{},"timestamp":"2024-04-29T21:48:37.475Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"INVALID_TOKEN","stack":"Error: INVALID_TOKEN\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-29T21:48:37.494Z"}
{"error":{"code":141,"message":"INVALID_TOKEN"},"functionName":"validate-token","level":"error","message":"Failed running cloud function validate-token for user AeGmyMY6oj with:\n  Input: {}\n  Error: {\"message\":\"INVALID_TOKEN\",\"code\":141}","params":{},"timestamp":"2024-04-29T21:51:28.677Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"INVALID_TOKEN","stack":"Error: INVALID_TOKEN\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-29T21:51:28.766Z"}
{"error":{"code":141,"message":"INVALID_TOKEN"},"functionName":"validate-token","level":"error","message":"Failed running cloud function validate-token for user AeGmyMY6oj with:\n  Input: {}\n  Error: {\"message\":\"INVALID_TOKEN\",\"code\":141}","params":{},"timestamp":"2024-04-29T21:54:15.900Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"INVALID_TOKEN","stack":"Error: INVALID_TOKEN\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-29T21:54:15.911Z"}
{"error":{"code":141,"message":"INVALID_TOKEN"},"functionName":"validate-token","level":"error","message":"Failed running cloud function validate-token for user AeGmyMY6oj with:\n  Input: {}\n  Error: {\"message\":\"INVALID_TOKEN\",\"code\":141}","params":{},"timestamp":"2024-04-29T21:54:18.379Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"INVALID_TOKEN","stack":"Error: INVALID_TOKEN\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)","timestamp":"2024-04-29T21:54:18.387Z"}
{"error":{"code":141,"message":"INVALID_TOKEN"},"functionName":"validate-token","level":"error","message":"Failed running cloud function validate-token for user AeGmyMY6oj with:\n  Input: {}\n  Error: {\"message\":\"INVALID_TOKEN\",\"code\":141}","params":{},"timestamp":"2024-04-29T21:56:18.467Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"INVALID_TOKEN","stack":"Error: INVALID_TOKEN\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-29T21:56:18.494Z"}
{"error":{"code":141,"message":"INVALID_TOKEN"},"functionName":"validate-token","level":"error","message":"Failed running cloud function validate-token for user AeGmyMY6oj with:\n  Input: {}\n  Error: {\"message\":\"INVALID_TOKEN\",\"code\":141}","params":{},"timestamp":"2024-04-29T21:56:54.118Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"INVALID_TOKEN","stack":"Error: INVALID_TOKEN\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-29T21:56:54.139Z"}
{"error":{"code":141,"message":"INVALID_TOKEN"},"functionName":"validate-token","level":"error","message":"Failed running cloud function validate-token for user AeGmyMY6oj with:\n  Input: {}\n  Error: {\"message\":\"INVALID_TOKEN\",\"code\":141}","params":{},"timestamp":"2024-04-29T21:56:56.321Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"INVALID_TOKEN","stack":"Error: INVALID_TOKEN\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)","timestamp":"2024-04-29T21:56:56.326Z"}
{"error":{"code":141,"message":"INVALID_TOKEN"},"functionName":"validate-token","level":"error","message":"Failed running cloud function validate-token for user AeGmyMY6oj with:\n  Input: {}\n  Error: {\"message\":\"INVALID_TOKEN\",\"code\":141}","params":{},"timestamp":"2024-04-29T22:00:31.627Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"INVALID_TOKEN","stack":"Error: INVALID_TOKEN\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-29T22:00:31.644Z"}
{"error":{"code":141,"message":"INVALID_TOKEN"},"functionName":"validate-token","level":"error","message":"Failed running cloud function validate-token for user AeGmyMY6oj with:\n  Input: {}\n  Error: {\"message\":\"INVALID_TOKEN\",\"code\":141}","params":{},"timestamp":"2024-04-29T22:01:29.261Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"INVALID_TOKEN","stack":"Error: INVALID_TOKEN\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-29T22:01:29.305Z"}
{"error":{"code":141,"message":"INVALID_TOKEN"},"functionName":"validate-token","level":"error","message":"Failed running cloud function validate-token for user AeGmyMY6oj with:\n  Input: {}\n  Error: {\"message\":\"INVALID_TOKEN\",\"code\":141}","params":{},"timestamp":"2024-04-29T22:01:31.955Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"INVALID_TOKEN","stack":"Error: INVALID_TOKEN\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)","timestamp":"2024-04-29T22:01:31.960Z"}
{"error":{"code":141,"message":"Error deleting objects: ParseError: 101 Object not found."},"functionName":"delete-chapter","level":"error","message":"Failed running cloud function delete-chapter for user AeGmyMY6oj with:\n  Input: {\"user\":\"AeGmyMY6oj\",\"chapterId\":\"e9HMDyLiAP\"}\n  Error: {\"message\":\"Error deleting objects: ParseError: 101 Object not found.\",\"code\":141}","params":{"chapterId":"e9HMDyLiAP","user":"AeGmyMY6oj"},"timestamp":"2024-04-29T22:30:15.348Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"Error deleting objects: ParseError: 101 Object not found.","stack":"Error: Error deleting objects: ParseError: 101 Object not found.\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-29T22:30:15.359Z"}
{"error":{"code":141,"message":"Error deleting objects: ParseError: 101 Object not found."},"functionName":"delete-chapter","level":"error","message":"Failed running cloud function delete-chapter for user AeGmyMY6oj with:\n  Input: {\"user\":\"AeGmyMY6oj\",\"chapterId\":\"6Uo2ygVytT\"}\n  Error: {\"message\":\"Error deleting objects: ParseError: 101 Object not found.\",\"code\":141}","params":{"chapterId":"6Uo2ygVytT","user":"AeGmyMY6oj"},"timestamp":"2024-04-30T02:45:30.054Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"Error deleting objects: ParseError: 101 Object not found.","stack":"Error: Error deleting objects: ParseError: 101 Object not found.\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-30T02:45:30.067Z"}
{"error":{"code":141,"message":"Error deleting objects: ParseError: 101 Object not found."},"functionName":"delete-chapter","level":"error","message":"Failed running cloud function delete-chapter for user AeGmyMY6oj with:\n  Input: {\"user\":\"AeGmyMY6oj\",\"chapterId\":\"6Uo2ygVytT\"}\n  Error: {\"message\":\"Error deleting objects: ParseError: 101 Object not found.\",\"code\":141}","params":{"chapterId":"6Uo2ygVytT","user":"AeGmyMY6oj"},"timestamp":"2024-04-30T02:45:37.101Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"Error deleting objects: ParseError: 101 Object not found.","stack":"Error: Error deleting objects: ParseError: 101 Object not found.\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-30T02:45:37.275Z"}
{"error":{"code":141,"message":"Error deleting objects: ParseError: 101 Object not found."},"functionName":"delete-chapter","level":"error","message":"Failed running cloud function delete-chapter for user AeGmyMY6oj with:\n  Input: {\"user\":\"AeGmyMY6oj\",\"chapterId\":\"6Uo2ygVytT\"}\n  Error: {\"message\":\"Error deleting objects: ParseError: 101 Object not found.\",\"code\":141}","params":{"chapterId":"6Uo2ygVytT","user":"AeGmyMY6oj"},"timestamp":"2024-04-30T02:51:15.882Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"Error deleting objects: ParseError: 101 Object not found.","stack":"Error: Error deleting objects: ParseError: 101 Object not found.\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-30T02:51:15.887Z"}
{"error":{"code":141,"message":"Error deleting objects: ParseError: 101 Object not found."},"functionName":"delete-chapter","level":"error","message":"Failed running cloud function delete-chapter for user AeGmyMY6oj with:\n  Input: {\"user\":\"AeGmyMY6oj\",\"chapterId\":\"6Uo2ygVytT\"}\n  Error: {\"message\":\"Error deleting objects: ParseError: 101 Object not found.\",\"code\":141}","params":{"chapterId":"6Uo2ygVytT","user":"AeGmyMY6oj"},"timestamp":"2024-04-30T02:54:21.704Z","user":"AeGmyMY6oj"}
{"code":141,"level":"error","message":"Error deleting objects: ParseError: 101 Object not found.","stack":"Error: Error deleting objects: ParseError: 101 Object not found.\n    at Object.resolveError (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\triggers.js:531:12)\n    at error (C:\\Users\\fabio\\AppData\\Roaming\\npm\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:99:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-04-30T02:54:21.709Z"}
